import { useState, useEffect } from 'react'; // Ensure useRef is included
import {PageRider} from '../PageRider'
import axios from 'axios';

export function RiderLogin({onSubmit}){
    const[submitted, setSubmitted] = useState(false)
    
    const [rider, setRider] = useState({
        id: null,
        username: '',
        phone_number: '',
        pickup_location: '',
        dropoff_location: '',
        driver_id: null,
    });

    const [formData, setFormData] = useState({
        name: '',
        phone: '',
        pickup: '',
        dropoff: '',
    
      });


    const handleChange = (e) => {
        const {name, value} = e.target;
        setFormData((prevData) => ({ ...prevData, [name]: value}));
    };

    const updateRiderData = (newData) => {
        setRider(prevState => ({
            ...prevState,
            ...newData
        }));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        console.log('Rider Information:', formData);
        setSubmitted(true)
        //axios.defaults.baseURL = 'http://localhost:5433'; // Replace with your server's base URL if necessary
        axios.defaults.baseURL = 'http://192.168.1.45:5433'; // Replace with your server's base URL if necessary

        try {
            console.log("Retrieving riders by phone number")
            const response = await axios.get(`/api/rider/by-phone/${formData.phone}`);
            console.log("GET request sent")
            if (response.data){
                console.log((response.data));
                console.log("riders by phone number retrieved")

                // Temporarily update driver object to form values for API call
                const newRiderData = {
                    id: null, // id will be auto-generated by the database
                    username: formData.name,
                    phone_number: formData.phone,
                    pickup_location: formData.pickup,
                    dropoff_location: formData.dropoff,
                    driver_id: null,
                };
                
                // if found, set newRiderData id and driver_id attributes
                newRiderData.id = response.data.id;
                newRiderData.driver_id = response.data.driver_id;

                updateRiderData({
                    id: response.data.id,
                    username: response.data.username,
                    phone_number: response.data.phone_number,
                    pickup_location: response.data.pickup_location,
                    dropoff_location: response.data.dropoff_location,
                    driver_id: response.data.driver_id,
                })
            
                // for now, use simple api call
            } else {
                console.log("Rider not found, creating a new driver...");

            }
            
        } catch (error) {
            if (error.response?.status === 404) {
                console.log('Rider not found in database, creating new rider...')

                // Temporarily update driver object to form values for API call
                const newRiderData = {
                    id: null, // id will be auto-generated by the database
                    username: formData.name,
                    phone_number: formData.phone,
                    pickup_location: formData.pickup,
                    dropoff_location: formData.dropoff,
                    driver_id: null,
                };

                console.log(newRiderData);
                
                try{
                    const insertResponse = await axios.post(`/api/rider/add/`, newRiderData);
                    console.log('Rider added successfully:', insertResponse.data.id);
        
                    // set the new rider's id attribute to the response from server
                    newRiderData.id = insertResponse.data.id
                    
                    updateRiderData({
                        ...newRiderData,
                        id: insertResponse.data.id,
                    });


                } catch (insertError){
                    console.log("error inserting new rider");
                }
                // insert new rider
                
            } else {
                console.error("Error retrieving or adding driver:", error);
            }
        
        }
    console.log('Rider logged in: ', rider)

    }
        
    useEffect(() => {
        const rider = window.localStorage.getItem('rider');
        const submitted = window.localStorage.getItem('submitted');
        if (rider) {
            setRider(JSON.parse(rider));
            setSubmitted(submitted);
        }
    }, []);
    useEffect(() => {
            if (rider.id !== null) {
                console.log('Rider logged in', rider);
            }
            window.localStorage.setItem('rider', JSON.stringify(rider));
            window.localStorage.setItem('submitted', submitted);
        }, [rider]); // This will log the driver when state changes and is not null


    console.log("In the RiderLogin")
    if(submitted){
        return(
            <div>
                {rider && rider.id ? (
                    <div>
                        <PageRider 
                            formData = {formData} 
                            rider={rider} 
                            setRider={setRider}
                            updateRiderData={updateRiderData}
                        />
                    </div>
                ) : (
                    <div>Loading....</div>
                )}
            </div>
            )
        }
    return (
        <div className = "design">
            <h1>Rider Information</h1>
            <i class="fa-solid fa-user idLogo"></i>
            <form onSubmit={handleSubmit}>
                <label>
                    Name:
                    <input
                        type="text"
                        name="name"
                        value={formData.name}
                        onChange={handleChange}
                        required
                    />
                </label>
                <br />
                <label>
                    Phone Number:
                    <input
                        //type="tel"
                        type="number"
                        name="phone"
                        value={formData.phone}
                        onChange={handleChange}
                        required
                        pattern="[0-9]{10}" 
                    />
                </label>
                <br />
                <label>
                    Pickup Location:
                    <input
                        type="text"
                        name="pickup"
                        value={formData.pickup}
                        onChange={handleChange}
                        required
                    />
                </label>
                <br/>
                <label>
                    Dropoff Location:
                    <input
                        type="text"
                        name="dropoff"
                        value={formData.dropoff}
                        onChange={handleChange}
                        required
                    />
                </label>
                <br />
                <button type="submit">Submit</button>
            </form>
        </div>
    );
    
}